"""
Seed FMECA — knowledge base iniziale per Failure Intelligence Engine.
Contiene 68 record realistici per 6 categorie di asset industriali.
"""
from backend.core.logging_config import get_logger

logger = get_logger(__name__)

FAILURE_MODES_SEED = [
    # ── MOTORE ELETTRICO (15 record) ─────────────────────────────────────────
    {
        "asset_type": "motore_elettrico", "component": "cuscinetti",
        "failure_mode": "usura cuscinetti",
        "failure_cause": "lubrificazione insufficiente o contaminazione da polvere/umidità",
        "failure_effect": "vibrazioni eccessive, rumore anomalo, surriscaldamento albero",
        "detection_method": "analisi vibrazioni, termografia, rumore anomalo udibile",
        "recommended_action": "sostituzione cuscinetti, verifica allineamento, rilubrificazione preventiva",
        "mtbf_hours": 20000, "severity": 7, "occurrence": 6, "detectability": 4,
    },
    {
        "asset_type": "motore_elettrico", "component": "avvolgimento statorico",
        "failure_mode": "surriscaldamento avvolgimento",
        "failure_cause": "sovraccarico prolungato, ventilazione insufficiente, cicli di avviamento frequenti",
        "failure_effect": "degradazione isolamento, cortocircuito, fermo motore",
        "detection_method": "termografia IR, misura temperatura, analisi corrente assorbita",
        "recommended_action": "verifica carico applicato, pulizia ventole, riduzione cicli avviamento",
        "mtbf_hours": 30000, "severity": 8, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "motore_elettrico", "component": "avvolgimento statorico",
        "failure_mode": "cortocircuito avvolgimento",
        "failure_cause": "degradazione isolamento per umidità, invecchiamento, surriscaldamento cronico",
        "failure_effect": "fermo improvviso, intervento protezioni, fumo/odore di bruciato",
        "detection_method": "misura resistenza isolamento (megaohmmetro), analisi corrente sbilanciata",
        "recommended_action": "revisione o sostituzione avvolgimento, verifica protezioni, analisi causa radice",
        "mtbf_hours": 50000, "severity": 9, "occurrence": 3, "detectability": 6,
    },
    {
        "asset_type": "motore_elettrico", "component": "isolamento",
        "failure_mode": "perdita isolamento verso terra",
        "failure_cause": "umidità, condensazione, contaminazione da olio/acqua",
        "failure_effect": "rischio scossa, intervento differenziale, danni avvolgimento",
        "detection_method": "test megaohmmetro (< 1 MΩ = critico), ispezione visiva",
        "recommended_action": "asciugatura avvolgimento in forno, verniciatura isolante, sigillatura ingressi cavo",
        "mtbf_hours": 40000, "severity": 8, "occurrence": 4, "detectability": 5,
    },
    {
        "asset_type": "motore_elettrico", "component": "rotore",
        "failure_mode": "vibrazione anomala rotore",
        "failure_cause": "squilibrio rotore, disallineamento con carico, usura cuscinetti",
        "failure_effect": "vibrazioni trasmesse alla struttura, usura accelerata cuscinetti",
        "detection_method": "analisi spettrale vibrazioni (accelerometro), bilanciamento dinamico",
        "recommended_action": "bilanciamento dinamico rotore, riallineamento albero, verifica giunto",
        "mtbf_hours": 25000, "severity": 6, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "motore_elettrico", "component": "alimentazione",
        "failure_mode": "mancanza fase",
        "failure_cause": "fusibile intervenuto, contattore difettoso, cavo interrotto",
        "failure_effect": "sovraccarico sulle altre fasi, surriscaldamento, fermo",
        "detection_method": "misura tensioni trifase al morsetto, controllo fusibili",
        "recommended_action": "verifica continuità cavi, sostituzione fusibili, controllo contattore",
        "mtbf_hours": 60000, "severity": 8, "occurrence": 3, "detectability": 2,
    },
    {
        "asset_type": "motore_elettrico", "component": "condensatori",
        "failure_mode": "condensatori avviamento esauriti",
        "failure_cause": "invecchiamento dielettrico, sovratensioni, cicli termici",
        "failure_effect": "motore non si avvia, coppia di spunto ridotta, ronzio",
        "detection_method": "misura capacità con capacimetro, test avviamento",
        "recommended_action": "sostituzione condensatori con stesso valore, verifica tensione nominale",
        "mtbf_hours": 15000, "severity": 5, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "motore_elettrico", "component": "tenute",
        "failure_mode": "perdita tenuta lato carico",
        "failure_cause": "usura anelli di tenuta, eccentricità albero, contaminazione",
        "failure_effect": "ingresso olio/umidità nei cuscinetti, contaminazione avvolgimento",
        "detection_method": "ispezione visiva perdite, analisi olio cuscinetti",
        "recommended_action": "sostituzione paraolio, verifica eccentricità albero",
        "mtbf_hours": 18000, "severity": 4, "occurrence": 6, "detectability": 4,
    },
    {
        "asset_type": "motore_elettrico", "component": "ventilazione",
        "failure_mode": "ventilazione ostruita",
        "failure_cause": "accumulo polvere/sporco sulle alette di raffreddamento",
        "failure_effect": "surriscaldamento progressivo, riduzione vita isolamento",
        "detection_method": "misura temperatura carcassa, ispezione visiva alette",
        "recommended_action": "pulizia alette raffreddamento con aria compressa, pianificare pulizia periodica",
        "mtbf_hours": 8000, "severity": 6, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "motore_elettrico", "component": "albero",
        "failure_mode": "disallineamento albero",
        "failure_cause": "montaggio impreciso, deformazione termica, usura supporti",
        "failure_effect": "vibrazioni, usura cuscinetti, sovraccarico giunto",
        "detection_method": "allineamento laser, analisi vibrazioni in frequenza",
        "recommended_action": "riallineamento con laser, verifica planità basamento",
        "mtbf_hours": 20000, "severity": 7, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "motore_elettrico", "component": "terminali",
        "failure_mode": "corrosione morsetti di collegamento",
        "failure_cause": "umidità, atmosfera corrosiva, ossidazione rame",
        "failure_effect": "resistenza di contatto elevata, surriscaldamento, perdita di potenza",
        "detection_method": "termocamera su morsettiera, misura resistenza di contatto",
        "recommended_action": "pulizia e serraggio morsetti, applicazione pasta antiossidante",
        "mtbf_hours": 12000, "severity": 5, "occurrence": 3, "detectability": 4,
    },
    {
        "asset_type": "motore_elettrico", "component": "albero",
        "failure_mode": "rottura linguetta di calettamento",
        "failure_cause": "sovraccarico impulsivo, inversioni frequenti, interferenza insufficiente",
        "failure_effect": "slittamento accoppiamento, perdita trasmissione coppia",
        "detection_method": "ispezione visiva giunto, rumore anomalo in avviamento",
        "recommended_action": "sostituzione linguetta con dimensione corretta, verifica interferenza",
        "mtbf_hours": 35000, "severity": 7, "occurrence": 2, "detectability": 5,
    },
    {
        "asset_type": "motore_elettrico", "component": "spazzole (CC)",
        "failure_mode": "usura spazzole (motore CC)",
        "failure_cause": "attrito meccanico normale, scintillio eccessivo, sporco collettore",
        "failure_effect": "scintillio, surriscaldamento collettore, instabilità velocità",
        "detection_method": "ispezione visiva lunghezza spazzole, misura caduta tensione",
        "recommended_action": "sostituzione spazzole, lucidatura collettore, verifica pressione molle",
        "mtbf_hours": 6000, "severity": 6, "occurrence": 6, "detectability": 3,
    },
    {
        "asset_type": "motore_elettrico", "component": "avvolgimento",
        "failure_mode": "umidità in avvolgimento",
        "failure_cause": "condensazione durante fermi prolungati, ambiente umido",
        "failure_effect": "riduzione resistenza isolamento, rischio cortocircuito",
        "detection_method": "megaohmmetro (misura IR), indice di polarizzazione",
        "recommended_action": "essiccazione in forno a 80°C per 24h, verniciatura isolante",
        "mtbf_hours": 0, "severity": 7, "occurrence": 3, "detectability": 6,
    },
    {
        "asset_type": "motore_elettrico", "component": "scudo/carcassa",
        "failure_mode": "rottura scudo porta cuscinetti",
        "failure_cause": "impatti meccanici, eccessiva forza assiale, fatica",
        "failure_effect": "perdita allineamento cuscinetti, vibrazione, rumore",
        "detection_method": "ispezione visiva, misura gioco assiale",
        "recommended_action": "sostituzione scudo, verifica causa forza assiale eccessiva",
        "mtbf_hours": 60000, "severity": 7, "occurrence": 2, "detectability": 4,
    },

    # ── POMPA CENTRIFUGA (15 record) ──────────────────────────────────────────
    {
        "asset_type": "pompa_centrifuga", "component": "girante",
        "failure_mode": "cavitazione girante",
        "failure_cause": "NPSH insufficiente, valvola aspirazione strozzata, altezza aspirazione eccessiva",
        "failure_effect": "rumore caratteristico (scricchiolio), erosione girante, riduzione portata",
        "detection_method": "rumore caratteristico, analisi vibrazioni, ispezione girante",
        "recommended_action": "aumento NPSH disponibile, verifica valvola aspirazione, riduzione altezza aspirazione",
        "mtbf_hours": 15000, "severity": 7, "occurrence": 6, "detectability": 4,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "tenuta meccanica",
        "failure_mode": "perdita tenuta meccanica",
        "failure_cause": "usura anelli di tenuta, particelle abrasive nel fluido, installazione errata",
        "failure_effect": "perdita di fluido, contaminazione ambiente, rischio sicurezza",
        "detection_method": "ispezione visiva perdite, misura consumo fluido di tenuta",
        "recommended_action": "sostituzione tenuta meccanica, filtrazione fluido, verifica installazione",
        "mtbf_hours": 12000, "severity": 6, "occurrence": 7, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "cuscinetti",
        "failure_mode": "usura cuscinetti pompa",
        "failure_cause": "carichi radiali/assiali eccessivi, lubrificazione insufficiente, disallineamento",
        "failure_effect": "vibrazioni, surriscaldamento, rumore, gioco eccessivo albero",
        "detection_method": "analisi vibrazioni, termografia, rumore anomalo",
        "recommended_action": "sostituzione cuscinetti, verifica allineamento pompa-motore, rilubrificazione",
        "mtbf_hours": 20000, "severity": 7, "occurrence": 5, "detectability": 4,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "girante",
        "failure_mode": "erosione girante",
        "failure_cause": "cavitazione cronica, fluido con particelle abrasive",
        "failure_effect": "riduzione efficienza, calo portata/prevalenza, sbilanciamento",
        "detection_method": "curva caratteristica degradata, ispezione visiva girante",
        "recommended_action": "sostituzione girante, trattamento antiusura fluido, eliminazione cavitazione",
        "mtbf_hours": 20000, "severity": 6, "occurrence": 4, "detectability": 5,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "corpo pompa",
        "failure_mode": "corrosione corpo pompa",
        "failure_cause": "fluido aggressivo, pH fuori range, temperatura elevata",
        "failure_effect": "perdite, riduzione spessore parete, rottura",
        "detection_method": "ispezione visiva, ultrasuoni spessimetro, analisi fluido",
        "recommended_action": "rivestimento anticorrosione, sostituzione corpo, controllo pH",
        "mtbf_hours": 40000, "severity": 7, "occurrence": 3, "detectability": 5,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "valvola aspirazione",
        "failure_mode": "ostruzione filtro aspirazione",
        "failure_cause": "accumulo detriti, scarsa manutenzione filtro",
        "failure_effect": "riduzione portata, cavitazione, sovraccarico motore",
        "detection_method": "misura depressione aspirazione, analisi portata",
        "recommended_action": "pulizia/sostituzione filtro, pianificare manutenzione periodica filtro",
        "mtbf_hours": 2000, "severity": 5, "occurrence": 7, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "albero",
        "failure_mode": "disallineamento pompa-motore",
        "failure_cause": "montaggio impreciso, deformazione termica basamento",
        "failure_effect": "vibrazioni eccessive, usura cuscinetti, usura tenuta",
        "detection_method": "allineamento laser, analisi vibrazioni spettrale",
        "recommended_action": "riallineamento con laser, verifica basamento e fondazioni",
        "mtbf_hours": 15000, "severity": 7, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "guarnizioni",
        "failure_mode": "perdita guarnizioni flange",
        "failure_cause": "invecchiamento materiale, sovrapressione, serraggio non uniforme",
        "failure_effect": "perdita fluido, contaminazione, calo pressione",
        "detection_method": "ispezione visiva perdite, test pressione",
        "recommended_action": "sostituzione guarnizioni, serraggio uniforme a croce con coppia calibrata",
        "mtbf_hours": 15000, "severity": 5, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "anelli di usura",
        "failure_mode": "usura anelli di tenuta interni",
        "failure_cause": "abrasione da particelle, normale ciclo di vita",
        "failure_effect": "ricircolo interno, calo portata/prevalenza, aumento temperatura",
        "detection_method": "misura portata e prevalenza vs curva caratteristica",
        "recommended_action": "sostituzione anelli di usura, verifica gioco",
        "mtbf_hours": 25000, "severity": 5, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "valvola mandata",
        "failure_mode": "colpo d'ariete da chiusura rapida",
        "failure_cause": "chiusura improvvisa valvola mandata, pompa che si ferma bruscamente",
        "failure_effect": "sovrapressione, danni tenute e giunti, rottura tubazione",
        "detection_method": "analisi transitori pressione, rumori impulsivi",
        "recommended_action": "installazione valvola antiritorno con smorzamento, chiusura graduale valvola",
        "mtbf_hours": 0, "severity": 8, "occurrence": 3, "detectability": 5,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "girante",
        "failure_mode": "ostruzione girante da corpo estraneo",
        "failure_cause": "detriti nel fluido, assenza filtro o filtro danneggiato",
        "failure_effect": "blocco girante, sovraccarico motore, fermo",
        "detection_method": "aumento corrente assorbita, calo portata improvviso",
        "recommended_action": "smontaggio e pulizia girante, installazione/verifica filtro aspirazione",
        "mtbf_hours": 8000, "severity": 7, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "basamento",
        "failure_mode": "allentamento bulloni basamento",
        "failure_cause": "vibrazioni, cicli termici, mancata manutenzione",
        "failure_effect": "aumento vibrazioni, disallineamento progressivo",
        "detection_method": "ispezione visiva bulloni, misura vibrazioni nel tempo",
        "recommended_action": "serraggio bulloni con coppia prescritta, uso rondelle elastiche",
        "mtbf_hours": 10000, "severity": 5, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "tenuta",
        "failure_mode": "surriscaldamento tenuta meccanica",
        "failure_cause": "fluido di flussaggio insufficiente, funzionamento a secco",
        "failure_effect": "usura accelerata anelli, perdita tenuta",
        "detection_method": "termocamera su area tenuta, verifica flussaggio",
        "recommended_action": "verifica portata flussaggio tenuta, protezione da funzionamento a secco",
        "mtbf_hours": 8000, "severity": 7, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "albero",
        "failure_mode": "fatica albero pompa",
        "failure_cause": "carichi ciclici eccessivi, corrosione localizzata, intagli",
        "failure_effect": "rottura albero, fermo improvviso, danni gravi",
        "detection_method": "analisi vibrazioni anomale, ispezione durante revisione",
        "recommended_action": "sostituzione albero, analisi causa carico eccessivo",
        "mtbf_hours": 80000, "severity": 9, "occurrence": 2, "detectability": 6,
    },
    {
        "asset_type": "pompa_centrifuga", "component": "motore pompa",
        "failure_mode": "pompa che lavora fuori curva (overload motore)",
        "failure_cause": "fluido più denso del previsto, valvole mal regolate, curva sistema cambiata",
        "failure_effect": "sovraccarico motore, intervento protezioni termiche",
        "detection_method": "misura corrente assorbita vs nominale, verifica punto operativo su curva",
        "recommended_action": "regolazione valvole, verifica viscosità fluido, ricalcolo punto operativo",
        "mtbf_hours": 0, "severity": 6, "occurrence": 4, "detectability": 3,
    },

    # ── COMPRESSORE (12 record) ───────────────────────────────────────────────
    {
        "asset_type": "compressore", "component": "valvole",
        "failure_mode": "rottura lamelle valvole",
        "failure_cause": "fatica, liquidi in aspirazione, corpi estranei, valvola sporca",
        "failure_effect": "perdita efficienza volumetrica, riduzione portata, surriscaldamento",
        "detection_method": "analisi temperatura scarico, misura portata, rumore anomalo",
        "recommended_action": "sostituzione lamelle valvole, installazione separatore liquidi",
        "mtbf_hours": 8000, "severity": 7, "occurrence": 6, "detectability": 4,
    },
    {
        "asset_type": "compressore", "component": "pistone/anelli",
        "failure_mode": "usura anelli pistone",
        "failure_cause": "lubrificazione insufficiente, contaminazione olio, cicli termici",
        "failure_effect": "aumento consumo olio, calo rendimento volumetrico, olio in aria compressa",
        "detection_method": "analisi olio aria compressa, misura consumo olio, temperatura scarico",
        "recommended_action": "sostituzione anelli pistone, verifica lubrificazione, analisi olio",
        "mtbf_hours": 15000, "severity": 6, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "compressore", "component": "filtro aria",
        "failure_mode": "filtro aria intasato",
        "failure_cause": "accumulo polvere, mancata sostituzione periodica",
        "failure_effect": "riduzione portata, surriscaldamento, aumento consumo energetico",
        "detection_method": "misura depressione filtro, ispezione visiva, portata ridotta",
        "recommended_action": "sostituzione filtro, rispettare intervalli manutenzione",
        "mtbf_hours": 2000, "severity": 5, "occurrence": 7, "detectability": 3,
    },
    {
        "asset_type": "compressore", "component": "cinghia/trasmissione",
        "failure_mode": "usura o rottura cinghia",
        "failure_cause": "tensionamento errato, disallineamento pulegge, invecchiamento",
        "failure_effect": "fermo compressore, slittamento, rumore",
        "detection_method": "ispezione visiva, misura tensione cinghia, rumore stridio",
        "recommended_action": "sostituzione cinghia, verifica tensione e allineamento pulegge",
        "mtbf_hours": 6000, "severity": 6, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "compressore", "component": "intercooler",
        "failure_mode": "intasamento intercooler",
        "failure_cause": "depositi calcare, contaminazione olio, scarsa manutenzione",
        "failure_effect": "temperatura aria compressa elevata, riduzione efficienza, allarme temperatura",
        "detection_method": "misura temperatura aria tra stadi, ispezione intercooler",
        "recommended_action": "pulizia intercooler, trattamento acqua raffreddamento",
        "mtbf_hours": 12000, "severity": 6, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "compressore", "component": "lubrificazione",
        "failure_mode": "degrado olio compressore",
        "failure_cause": "invecchiamento termoossidativo, contaminazione acqua, intervalli troppo lunghi",
        "failure_effect": "usura accelerata parti meccaniche, depositi, surriscaldamento",
        "detection_method": "analisi olio (viscosità, acidità, TAN), colore olio",
        "recommended_action": "sostituzione olio secondo intervalli, analisi olio periodica",
        "mtbf_hours": 4000, "severity": 7, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "compressore", "component": "separatore olio",
        "failure_mode": "separatore olio saturo",
        "failure_cause": "superamento vita utile, olio degradato",
        "failure_effect": "olio in aria compressa, contaminazione utenze",
        "detection_method": "misura contenuto olio aria compressa, analisi aria",
        "recommended_action": "sostituzione elemento separatore, analisi olio",
        "mtbf_hours": 4000, "severity": 6, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "compressore", "component": "valvola di sicurezza",
        "failure_mode": "valvola sicurezza che scarica",
        "failure_cause": "pressione di taratura superata, valvola deteriorata, overpressione sistema",
        "failure_effect": "perdita aria, rumore, rischio sicurezza se valvola non richiude",
        "detection_method": "rumore scarico aria, misura pressione sistema",
        "recommended_action": "verifica taratura, sostituzione valvola, analisi causa overpressione",
        "mtbf_hours": 0, "severity": 8, "occurrence": 3, "detectability": 2,
    },
    {
        "asset_type": "compressore", "component": "cuscinetti",
        "failure_mode": "usura cuscinetti albero compressore",
        "failure_cause": "lubrificazione insufficiente, carichi eccessivi, contaminazione olio",
        "failure_effect": "vibrazioni, rumore, surriscaldamento, gioco eccessivo",
        "detection_method": "analisi vibrazioni, termografia cuscinetti",
        "recommended_action": "sostituzione cuscinetti, analisi causa, verifica lubrificazione",
        "mtbf_hours": 25000, "severity": 7, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "compressore", "component": "tenute albero",
        "failure_mode": "perdita tenuta olio albero",
        "failure_cause": "usura paraolio, pressione eccessiva, eccentricità albero",
        "failure_effect": "perdita olio, contaminazione ambiente, riduzione livello olio",
        "detection_method": "ispezione visiva perdite olio, livello olio calante",
        "recommended_action": "sostituzione paraolio, verifica eccentricità e pressione carter",
        "mtbf_hours": 15000, "severity": 5, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "compressore", "component": "sistema raffreddamento",
        "failure_mode": "surriscaldamento compressore",
        "failure_cause": "ventilazione locale insufficiente, intercooler sporco, olio basso",
        "failure_effect": "intervento termostato/temperatura, fermo, danni agli anelli",
        "detection_method": "allarme temperatura, termocamera, misura temperatura scarico",
        "recommended_action": "miglioramento ventilazione locale, pulizia intercooler, verifica livello olio",
        "mtbf_hours": 0, "severity": 8, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "compressore", "component": "pressostato/controllo",
        "failure_mode": "pressostato fuori taratura",
        "failure_cause": "vibrazioni, invecchiamento, umidità nel circuito controllo",
        "failure_effect": "pressione di sistema fuori range, ciclo errato on/off",
        "detection_method": "misura pressione con manometro campione, confronto set-point",
        "recommended_action": "taratura o sostituzione pressostato, verifica circuito pneumatico controllo",
        "mtbf_hours": 20000, "severity": 5, "occurrence": 3, "detectability": 3,
    },

    # ── QUADRO ELETTRICO (10 record) ──────────────────────────────────────────
    {
        "asset_type": "quadro_elettrico", "component": "contattori",
        "failure_mode": "usura contatti contattore",
        "failure_cause": "numero cicli superato, corrente di inserzione eccessiva, archi elettrici",
        "failure_effect": "saldatura contatti, mancata apertura, surriscaldamento",
        "detection_method": "termocamera su contattori in servizio, misura resistenza contatti",
        "recommended_action": "sostituzione contattore, verifica dimensionamento per carico reale",
        "mtbf_hours": 1000000, "severity": 7, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "quadro_elettrico", "component": "fusibili",
        "failure_mode": "fusibile intervenuto",
        "failure_cause": "sovraccarico, cortocircuito, invecchiamento, fusibile sottodimensionato",
        "failure_effect": "fermo utenza, apertura circuito, perdita fase",
        "detection_method": "verifica visiva (indicatore), misura continuità",
        "recommended_action": "sostituzione fusibile della stessa taglia, ricerca e rimozione causa",
        "mtbf_hours": 0, "severity": 6, "occurrence": 4, "detectability": 2,
    },
    {
        "asset_type": "quadro_elettrico", "component": "interruttori magnetotermici",
        "failure_mode": "scatto termico interruttore",
        "failure_cause": "sovraccarico prolungato, temperatura ambiente elevata",
        "failure_effect": "fermo circuito, perdita alimentazione utenza",
        "detection_method": "verifica posizione leva, misura corrente prima dello scatto",
        "recommended_action": "ripristino dopo raffreddamento, analisi causa sovraccarico",
        "mtbf_hours": 0, "severity": 5, "occurrence": 5, "detectability": 2,
    },
    {
        "asset_type": "quadro_elettrico", "component": "PLC/HMI",
        "failure_mode": "guasto modulo I/O PLC",
        "failure_cause": "sovratensioni, corrosione, invecchiamento componenti",
        "failure_effect": "perdita segnali, blocco automazione, allarmi",
        "detection_method": "diagnostica PLC, verifica LED modulo, mappa I/O",
        "recommended_action": "sostituzione modulo I/O, backup programma, verifica protezioni SPD",
        "mtbf_hours": 50000, "severity": 8, "occurrence": 3, "detectability": 3,
    },
    {
        "asset_type": "quadro_elettrico", "component": "trasformatore",
        "failure_mode": "surriscaldamento trasformatore",
        "failure_cause": "sovraccarico, ventilazione insufficiente, armoniche di rete",
        "failure_effect": "degradazione isolamento, intervento termostato, guasto",
        "detection_method": "termocamera, misura temperatura avvolgimenti, analisi armonica",
        "recommended_action": "riduzione carico, miglioramento ventilazione, filtro armonico",
        "mtbf_hours": 100000, "severity": 8, "occurrence": 3, "detectability": 4,
    },
    {
        "asset_type": "quadro_elettrico", "component": "cablaggio",
        "failure_mode": "deterioramento isolamento cavi",
        "failure_cause": "temperatura elevata, roditori, abrasione meccanica, invecchiamento",
        "failure_effect": "dispersioni, cortocircuiti, rischio incendio",
        "detection_method": "megaohmmetro, ispezione visiva cablaggio",
        "recommended_action": "sostituzione cavi danneggiati, protezione da roditori, verifica temperature",
        "mtbf_hours": 80000, "severity": 8, "occurrence": 3, "detectability": 5,
    },
    {
        "asset_type": "quadro_elettrico", "component": "messa a terra",
        "failure_mode": "continuità terra interrotta",
        "failure_cause": "corrosione conduttore, allentamento morsetto, danno meccanico",
        "failure_effect": "rischio sicurezza, dispersioni non rilevate, interferenze EMC",
        "detection_method": "misura resistenza terra (<1 Ohm), verifica continuità visiva",
        "recommended_action": "ripristino continuità, serraggio morsetti, verifica percorso terra",
        "mtbf_hours": 0, "severity": 9, "occurrence": 2, "detectability": 5,
    },
    {
        "asset_type": "quadro_elettrico", "component": "SPD (scaricatori)",
        "failure_mode": "scaricatore sovratensione esaurito",
        "failure_cause": "evento di sovratensione, fine vita",
        "failure_effect": "perdita protezione, successivo evento danneggia apparecchiature",
        "detection_method": "indicatore visivo su SPD, test con strumento specifico",
        "recommended_action": "sostituzione SPD, verifica numero eventi registrati",
        "mtbf_hours": 0, "severity": 7, "occurrence": 3, "detectability": 2,
    },
    {
        "asset_type": "quadro_elettrico", "component": "ventilazione quadro",
        "failure_mode": "ventilatore quadro guasto",
        "failure_cause": "usura cuscinetti ventilatore, filtro ostruito, fatica",
        "failure_effect": "surriscaldamento interno quadro, riduzione vita componenti",
        "detection_method": "termocamera su quadro chiuso, verifica funzionamento ventilatore",
        "recommended_action": "sostituzione ventilatore, pulizia filtri di ventilazione",
        "mtbf_hours": 15000, "severity": 6, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "quadro_elettrico", "component": "relè termico",
        "failure_mode": "relè termico fuori taratura",
        "failure_cause": "vibrazioni, temperatura ambiente variabile, invecchiamento",
        "failure_effect": "protezione non efficace (scatta troppo presto o troppo tardi)",
        "detection_method": "test con corrente campione, confronto con valore nominale",
        "recommended_action": "ritaratura o sostituzione relè, compensazione temperatura ambiente",
        "mtbf_hours": 30000, "severity": 6, "occurrence": 3, "detectability": 4,
    },

    # ── VALVOLA INDUSTRIALE (8 record) ────────────────────────────────────────
    {
        "asset_type": "valvola_industriale", "component": "premistoppa",
        "failure_mode": "perdita premistoppa",
        "failure_cause": "usura guarnizione, serraggio insufficiente, compatibilità materiale",
        "failure_effect": "perdita fluido, contaminazione, rischio sicurezza",
        "detection_method": "ispezione visiva perdite, misura emissioni (VOC per fluidi pericolosi)",
        "recommended_action": "serraggio premistoppa o sostituzione guarnizione, verifica materiale",
        "mtbf_hours": 10000, "severity": 6, "occurrence": 6, "detectability": 3,
    },
    {
        "asset_type": "valvola_industriale", "component": "sede/disco",
        "failure_mode": "usura sede e disco valvola",
        "failure_cause": "erosione da fluido, cavitazione, corrosione, particelle abrasive",
        "failure_effect": "mancata tenuta in chiusura, by-pass interno",
        "detection_method": "test tenuta con misura portata, ispezione durante revisione",
        "recommended_action": "rettifica o sostituzione sede/disco, filtrazione fluido",
        "mtbf_hours": 20000, "severity": 7, "occurrence": 5, "detectability": 5,
    },
    {
        "asset_type": "valvola_industriale", "component": "attuatore pneumatico",
        "failure_mode": "guasto attuatore pneumatico",
        "failure_cause": "perdita aria pilota, rottura membrana, contaminazione aria",
        "failure_effect": "valvola non risponde, posizione di sicurezza non raggiunta",
        "detection_method": "verifica segnale aria, test apertura/chiusura manuale",
        "recommended_action": "verifica alimentazione aria, sostituzione membrana, filtrazione aria",
        "mtbf_hours": 30000, "severity": 8, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "valvola_industriale", "component": "corpo valvola",
        "failure_mode": "corrosione esterna corpo valvola",
        "failure_cause": "ambiente corrosivo, umidità, temperatura, mancata protezione",
        "failure_effect": "riduzione spessore, rischio rottura, perdite",
        "detection_method": "ispezione visiva, ultrasuoni spessimetro",
        "recommended_action": "verniciatura/rivestimento protettivo, sostituzione se critico",
        "mtbf_hours": 50000, "severity": 7, "occurrence": 4, "detectability": 5,
    },
    {
        "asset_type": "valvola_industriale", "component": "posizionatore",
        "failure_mode": "posizionatore non calibrato",
        "failure_cause": "vibrazioni, variazione condizioni operative, invecchiamento",
        "failure_effect": "valvola non raggiunge posizione comandata, controllo impreciso",
        "detection_method": "confronto segnale comando vs posizione effettiva",
        "recommended_action": "ricalibratura posizionatore, verifica segnale 4-20mA",
        "mtbf_hours": 20000, "severity": 5, "occurrence": 4, "detectability": 3,
    },
    {
        "asset_type": "valvola_industriale", "component": "stelo",
        "failure_mode": "stelo valvola bloccato",
        "failure_cause": "corrosione, depositi, mancato esercizio per lungo periodo",
        "failure_effect": "valvola non manovrabile, posizione bloccata",
        "detection_method": "tentativo manovra, misura coppia di apertura",
        "recommended_action": "lubrificazione forzata, manovra manuale ripetuta, sostituzione se necessario",
        "mtbf_hours": 0, "severity": 7, "occurrence": 3, "detectability": 4,
    },
    {
        "asset_type": "valvola_industriale", "component": "guarnizioni",
        "failure_mode": "perdita guarnizioni flangia",
        "failure_cause": "invecchiamento, sovrapressione, cicli termici, serraggio non uniforme",
        "failure_effect": "perdita fluido in flangia, contaminazione, rischio sicurezza",
        "detection_method": "ispezione visiva, test pressione",
        "recommended_action": "sostituzione guarnizione, serraggio a coppia con schema a croce",
        "mtbf_hours": 20000, "severity": 6, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "valvola_industriale", "component": "attuatore elettrico",
        "failure_mode": "guasto attuatore elettrico",
        "failure_cause": "motore bruciato, frizione slittata, encoder guasto",
        "failure_effect": "valvola non comandabile, posizione incerta",
        "detection_method": "diagnostica attuatore, allarme su DCS, verifica manuale",
        "recommended_action": "sostituzione attuatore o componente guasto, verifica alimentazione",
        "mtbf_hours": 40000, "severity": 7, "occurrence": 3, "detectability": 3,
    },

    # ── NASTRO TRASPORTATORE (8 record) ───────────────────────────────────────
    {
        "asset_type": "nastro_trasportatore", "component": "cinghia/nastro",
        "failure_mode": "usura o lacerazione nastro",
        "failure_cause": "sovraccarico, materiale abrasivo, oggetti taglienti, disallineamento",
        "failure_effect": "fuoriuscita materiale, fermo impianto, danni nastro",
        "detection_method": "ispezione visiva nastro, rilevatori di strappo",
        "recommended_action": "riparazione o sostituzione nastro, verifica causa (oggetti, abrasione)",
        "mtbf_hours": 10000, "severity": 7, "occurrence": 5, "detectability": 3,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "rulli portanti",
        "failure_mode": "grippaggio rulli",
        "failure_cause": "usura cuscinetti rullo, contaminazione, mancata lubrificazione",
        "failure_effect": "usura nastro sul punto, attrito elevato, surriscaldamento",
        "detection_method": "ispezione visiva rulli in rotazione, termocamera",
        "recommended_action": "sostituzione rulli grippati, verifica frequenza ispezione",
        "mtbf_hours": 8000, "severity": 5, "occurrence": 7, "detectability": 3,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "motoriduttore",
        "failure_mode": "guasto motoriduttore",
        "failure_cause": "sovraccarico, olio riduttore esaurito, usura ingranaggi",
        "failure_effect": "fermo nastro, impossibilità di avviamento",
        "detection_method": "rumore anomalo, surriscaldamento riduttore, analisi olio",
        "recommended_action": "sostituzione/revisione riduttore, cambio olio periodico",
        "mtbf_hours": 20000, "severity": 8, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "tensionamento",
        "failure_mode": "tensione nastro insufficiente",
        "failure_cause": "allungamento nastro, sistema tensionamento non regolato",
        "failure_effect": "slittamento nastro su puleggia motrice, usura accelerata",
        "detection_method": "ispezione freccia nastro, slittamento visibile",
        "recommended_action": "regolazione tendicinghia, verifica stato nastro",
        "mtbf_hours": 0, "severity": 5, "occurrence": 6, "detectability": 3,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "pulegge",
        "failure_mode": "usura rivestimento puleggia motrice",
        "failure_cause": "abrasione, materiale tra nastro e puleggia, slittamento cronico",
        "failure_effect": "riduzione trazione, slittamento nastro",
        "detection_method": "ispezione visiva rivestimento, misura spessore",
        "recommended_action": "sostituzione rivestimento o puleggia, verifica tensione nastro",
        "mtbf_hours": 15000, "severity": 6, "occurrence": 4, "detectability": 4,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "raschiatori",
        "failure_mode": "raschiatore non efficace",
        "failure_cause": "usura lama, mancata regolazione, materiale diverso",
        "failure_effect": "accumulo materiale sul nastro, sporco sotto cinghia, usura nastro",
        "detection_method": "ispezione visiva accumulo materiale",
        "recommended_action": "sostituzione lama raschiatore, regolazione pressione",
        "mtbf_hours": 3000, "severity": 4, "occurrence": 7, "detectability": 3,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "cinghia/nastro",
        "failure_mode": "disallineamento nastro",
        "failure_cause": "rulli non allineati, carico non centrato, nastro usurato asimmetricamente",
        "failure_effect": "nastro che sormonta la sponda, usura bordo nastro",
        "detection_method": "ispezione visiva allineamento, sensori di deviazione",
        "recommended_action": "regolazione rulli di ritorno/deviatori, verifica centratura carico",
        "mtbf_hours": 0, "severity": 6, "occurrence": 6, "detectability": 3,
    },
    {
        "asset_type": "nastro_trasportatore", "component": "struttura/telai",
        "failure_mode": "corrosione struttura portante",
        "failure_cause": "ambiente umido/aggressivo, mancata verniciatura, condensazione",
        "failure_effect": "riduzione resistenza strutturale, rischio cedimento",
        "detection_method": "ispezione visiva, spessimetro ultrasonico",
        "recommended_action": "trattamento antiruggine, verniciatura, sostituzione elementi critici",
        "mtbf_hours": 80000, "severity": 7, "occurrence": 4, "detectability": 5,
    },
]


def seed_failure_modes(db) -> None:
    """Popola la tabella failure_modes con dati FMECA standard. Idempotente."""
    from backend.db.modelli import FailureMode
    if db.query(FailureMode).first():
        logger.info("Seed failure_modes: tabella gia popolata, skip.")
        return

    for record in FAILURE_MODES_SEED:
        sev = record["severity"]
        occ = record["occurrence"]
        det = record["detectability"]
        fm = FailureMode(
            asset_type=record["asset_type"],
            component=record["component"],
            failure_mode=record["failure_mode"],
            failure_cause=record.get("failure_cause"),
            failure_effect=record.get("failure_effect"),
            detection_method=record.get("detection_method"),
            recommended_action=record.get("recommended_action"),
            mtbf_hours=record.get("mtbf_hours"),
            severity=sev,
            occurrence=occ,
            detectability=det,
            rpn=sev * occ * det,
            peso_appreso=1.0,
            source="seed",
            is_global=True,
            tenant_id=None,
        )
        db.add(fm)

    db.commit()
    logger.info("Seed failure_modes: inseriti %d record FMECA.", len(FAILURE_MODES_SEED))
