"""Add system logs and email config security

Revision ID: 35093982921a
Revises: fa1c5b675293
Create Date: 2026-04-04 20:52:32.277206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35093982921a'
down_revision: Union[str, Sequence[str], None] = 'fa1c5b675293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
