"""add parent_id and diagnosi_eseguita to ticket

Revision ID: 36e5d8a7ecb9
Revises: 5ee6edaf8646
Create Date: 2026-03-28 10:21:46.356886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e5d8a7ecb9'
down_revision: Union[str, Sequence[str], None] = '5ee6edaf8646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diagnosi_eseguita', sa.Boolean(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'CM'"))
        batch_op.create_foreign_key('fk_ticket_parent_id', 'ticket', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_parent_id', type_='foreignkey')
        batch_op.alter_column('tipo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'CM'"))
        batch_op.drop_column('diagnosi_eseguita')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
