"""m1_m2_asset_criticita_costo_fermo_ricambi_ticket

Revision ID: 3b5b37e1e43f
Revises: 92deed855516
Create Date: 2026-05-24 21:11:41.297245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5b37e1e43f'
down_revision: Union[str, Sequence[str], None] = '92deed855516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_orario_fermo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('codice_ricambio_esterno', sa.String(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ricambio_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('in_attesa_ricambio', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('in_attesa_ricambio')
        batch_op.drop_column('ricambio_note')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('codice_ricambio_esterno')
        batch_op.drop_column('costo_orario_fermo')

    # ### end Alembic commands ###
