"""ristrutturazione_piani_multiasset_v2

Revision ID: 92deed855516
Revises: 20260411001
Create Date: 2026-04-12 14:34:24.646198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92deed855516'
down_revision: Union[str, Sequence[str], None] = '20260411001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tabella già esistente da tentativo precedente
    # op.create_table('piani_assets_association',
    # sa.Column('piano_id', sa.Integer(), nullable=False),
    # sa.Column('asset_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    # sa.ForeignKeyConstraint(['piano_id'], ['piani_manutenzione.id'], ),
    # sa.PrimaryKeyConstraint('piano_id', 'asset_id')
    # )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_tenant_area'))

    with op.batch_alter_table('attivita_manutenzione', schema=None) as batch_op:
        batch_op.alter_column('last_generated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('next_due_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_attivita_manutenzione_codice'), ['codice'], unique=False)
        batch_op.create_index(batch_op.f('ix_attivita_manutenzione_piano_id'), ['piano_id'], unique=False)
        batch_op.create_foreign_key('fk_attivita_manutenzione_piano_id', 'piani_manutenzione', ['piano_id'], ['id'])

    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_plans_tenant_status'))
        batch_op.create_index(batch_op.f('ix_generated_plans_plan_number'), ['plan_number'], unique=False)

    with op.batch_alter_table('manuali', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piano_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_manuali_piano_id'), ['piano_id'], unique=False)
        batch_op.create_foreign_key('fk_manuali_piano_id', 'piani_manutenzione', ['piano_id'], ['id'])

    with op.batch_alter_table('tecnici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tecnici_tenant_stato'))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_ticket_tenant_priorita'))
        batch_op.drop_index(batch_op.f('ix_ticket_tenant_stato'))
        batch_op.create_foreign_key('fk_ticket_piano_manutenzione_id', 'piani_manutenzione', ['piano_manutenzione_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_ticket_tenant_stato'), ['tenant_id', 'stato'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_tenant_priorita'), ['tenant_id', 'priorita'], unique=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('tecnici', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tecnici_tenant_stato'), ['tenant_id', 'stato'], unique=False)

    with op.batch_alter_table('manuali', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_manuali_piano_id'))
        batch_op.drop_column('piano_id')

    with op.batch_alter_table('generated_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_plans_plan_number'))
        batch_op.create_index(batch_op.f('ix_generated_plans_tenant_status'), ['tenant_id', 'status'], unique=False)

    with op.batch_alter_table('attivita_manutenzione', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attivita_manutenzione_piano_id'))
        batch_op.drop_index(batch_op.f('ix_attivita_manutenzione_codice'))
        batch_op.alter_column('next_due_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_generated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_tenant_area'), ['tenant_id', 'area'], unique=False)

    op.drop_table('piani_assets_association')
    # ### end Alembic commands ###
