"""M4-M5 procedure note-asset check-primo-livello attestati

Revision ID: c8b3fc6efac0
Revises: 3b5b37e1e43f
Create Date: 2026-05-24 21:40:26.613063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b3fc6efac0'
down_revision: Union[str, Sequence[str], None] = '3b5b37e1e43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
