"""Initial master baseline

Revision ID: fa1c5b675293
Revises: 
Create Date: 2026-04-04 19:52:26.556139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1c5b675293'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('manuali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_file', sa.String(), nullable=True),
    sa.Column('pagine', sa.Integer(), nullable=True),
    sa.Column('metodo_lettura', sa.String(), nullable=True),
    sa.Column('testo_raw', sa.Text(), nullable=True),
    sa.Column('json_estratto', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manuali', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuali_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuali_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('siti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('ubicazione', sa.String(), nullable=True),
    sa.Column('citta', sa.String(), nullable=True),
    sa.Column('paese', sa.String(), nullable=True),
    sa.Column('responsabile', sa.String(), nullable=True),
    sa.Column('telefono_responsabile', sa.String(), nullable=True),
    sa.Column('email_responsabile', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siti_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siti_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('ruolo', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utenti_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utenti_username'), ['username'], unique=True)

    op.create_table('impianti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sito_id', sa.Integer(), nullable=True),
    sa.Column('tipologia', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sito_id'], ['siti.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impianti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impianti_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impianti_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tecnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('competenze', sa.String(), nullable=True),
    sa.Column('ore_giornaliere', sa.Integer(), nullable=True),
    sa.Column('cognome', sa.String(), nullable=True),
    sa.Column('stato', sa.String(), nullable=True),
    sa.Column('orario_inizio', sa.String(), nullable=True),
    sa.Column('orario_fine', sa.String(), nullable=True),
    sa.Column('limitazioni_orarie', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tecnici', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tecnici_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tecnici_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('vincolo_orario', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('codice', sa.String(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('anno', sa.Integer(), nullable=True),
    sa.Column('impianto_id', sa.Integer(), nullable=True),
    sa.Column('limitazioni', sa.Text(), nullable=True),
    sa.Column('stato', sa.String(), nullable=True),
    sa.Column('stato_changed_at', sa.DateTime(), nullable=True),
    sa.Column('weather_sunny_required', sa.Boolean(), nullable=True),
    sa.Column('weather_max_wind_kmh', sa.Float(), nullable=True),
    sa.Column('weather_max_rain_mm', sa.Float(), nullable=True),
    sa.Column('anno_installazione', sa.Integer(), nullable=True),
    sa.Column('anno_produzione', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modello', sa.String(), nullable=True),
    sa.Column('matricola', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('fornitore', sa.String(), nullable=True),
    sa.Column('data_acquisto', sa.Date(), nullable=True),
    sa.Column('data_scadenza_garanzia', sa.Date(), nullable=True),
    sa.Column('vincoli_operativi', sa.Text(), nullable=True),
    sa.Column('vincoli_manutenzione', sa.Text(), nullable=True),
    sa.Column('note_tecniche', sa.Text(), nullable=True),
    sa.Column('criticita', sa.String(), nullable=True),
    sa.Column('posizione_fisica', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impianto_id'], ['impianti.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_codice'), ['codice'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tecnici_assenze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('data_inizio', sa.DateTime(), nullable=False),
    sa.Column('data_fine', sa.DateTime(), nullable=False),
    sa.Column('tipo_assenza', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tecnici_assenze', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tecnici_assenze_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tecnici_assenze_tecnico_id'), ['tecnico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tecnici_assenze_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('attivita_manutenzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('manuale_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('frequenza_giorni', sa.Integer(), nullable=True),
    sa.Column('durata_ore', sa.Float(), nullable=True),
    sa.Column('priorita', sa.String(), nullable=True),
    sa.Column('origine', sa.String(), nullable=True),
    sa.Column('ultima_esecuzione', sa.DateTime(), nullable=True),
    sa.Column('prossima_scadenza', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['manuale_id'], ['manuali.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attivita_manutenzione', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attivita_manutenzione_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attivita_manutenzione_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('email_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('imap_server', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('default_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_config_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_config_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('priorita', sa.String(), nullable=True),
    sa.Column('stato', sa.String(), nullable=True),
    sa.Column('durata_stimata_ore', sa.Float(), nullable=True),
    sa.Column('fascia_oraria', sa.String(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('attivita_manutenzione_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_finish', sa.DateTime(), nullable=True),
    sa.Column('execution_start', sa.DateTime(), nullable=True),
    sa.Column('execution_finish', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('diagnosi_eseguita', sa.Boolean(), nullable=True),
    sa.Column('firma_percorso', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['attivita_manutenzione_id'], ['attivita_manutenzione.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('analisi_guasti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.String(), nullable=True),
    sa.Column('sintomi', sa.Text(), nullable=True),
    sa.Column('analisi_json', sa.Text(), nullable=True),
    sa.Column('ai_utilizzata', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analisi_guasti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisi_guasti_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analisi_guasti_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ticket_allegati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('nome_file', sa.String(length=255), nullable=False),
    sa.Column('percorso', sa.String(length=512), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('dimensione_bytes', sa.Integer(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_allegati', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_allegati_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_allegati_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_allegati', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_allegati_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_allegati_id'))

    op.drop_table('ticket_allegati')
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_id'))

    op.drop_table('diagnostic_sessions')
    with op.batch_alter_table('analisi_guasti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisi_guasti_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_analisi_guasti_id'))

    op.drop_table('analisi_guasti')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_id'))

    op.drop_table('ticket')
    with op.batch_alter_table('email_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_config_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_email_config_id'))

    op.drop_table('email_config')
    with op.batch_alter_table('attivita_manutenzione', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attivita_manutenzione_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_attivita_manutenzione_id'))

    op.drop_table('attivita_manutenzione')
    with op.batch_alter_table('tecnici_assenze', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tecnici_assenze_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tecnici_assenze_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_tecnici_assenze_id'))

    op.drop_table('tecnici_assenze')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_asset_id'))
        batch_op.drop_index(batch_op.f('ix_asset_codice'))

    op.drop_table('asset')
    with op.batch_alter_table('tecnici', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tecnici_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tecnici_id'))

    op.drop_table('tecnici')
    with op.batch_alter_table('impianti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impianti_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_impianti_id'))

    op.drop_table('impianti')
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utenti_username'))
        batch_op.drop_index(batch_op.f('ix_utenti_id'))

    op.drop_table('utenti')
    with op.batch_alter_table('siti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siti_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_siti_id'))

    op.drop_table('siti')
    with op.batch_alter_table('manuali', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manuali_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_manuali_id'))

    op.drop_table('manuali')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
